### ISSUE TITLE
code regression suite

### ISSUE THREAD

**Issue by markallen3** [csev/py4e#104]
As time advances, newer versions of python will be released. It's nice to know that the behavior of the code samples or assignments doesn't change or if it does, it can be quickly isolated and fixed. 
Maybe this is overkill, what do you think?

**Comment by eah13** [comment]
It'd definitely be nice to get some automated tests for sample program state and output.  Is this something you'd be willing/able to submit a PR for?

**Comment by markallen3** [comment]
i still feel this is a good idea. There are so many things competing for my attention, but I didn't want this one to just slide on by.
