### ISSUE TITLE
Small typos in chapter 2 of book3

### ISSUE THREAD

**Issue by smp3142** [csev/py4e#124]
`word *in* words*:*\  *print* word`
perhaps should be
`*for* word *in* words*:*\  *print* word`

In Exercise 4
`1 + 2 \* 5`
The * is escaped and perhaps should just be
`1 + 2 * 5`

**Comment by eah13** [comment]
Thanks! will hit this with my upcoming edits.

@smp3142 I couldn't find the first typo you report.  It looks correct to me in Chapter 2.

Note: the escaped `*` is in Chapter 2
