### ISSUE TITLE
Chapter 6 Strings

### ISSUE THREAD

**Issue by edshav** [csev/py4e#139]
![screenshot from 2017-10-05 07-51-52](https://user-images.githubusercontent.com/31659942/31211559-b4f7226a-a9a2-11e7-91fd-d4d52fbabeff.png)

**Comment by DontTreadMe** [comment]
![screenshot from 2017-10-05 07-59-51](https://user-images.githubusercontent.com/31659942/31211627-4de85340-a9a3-11e7-988f-8d0600624e03.png)

**Comment by DontTreadMe** [comment]
![screenshot from 2017-10-06 06-50-04](https://user-images.githubusercontent.com/31659942/31262306-c424acba-aa62-11e7-81d3-6cc8cc5caade.png)

**Comment by csev** [comment]
Thanks.  These are fixed in the latest version of the book.
