### ISSUE TITLE
python 2 syntax in book3 ch2

### ISSUE THREAD

**Issue by cadenzasong** [csev/py4e#167]
Cannot push a fix branch to the repo, the diff:

--- a/book3/02-variables.mkd
+++ b/book3/02-variables.mkd
@@ -649,7 +649,7 @@ at you:
 
 <pre>
 <b>for</b> word <b>in</b> words<b>:</b>
-    <b>print</b> word
+    <b>print</b>(word)
 </pre>

**Comment by srcatto** [comment]
Tried again, still failed.

**Comment by cadenzasong** [comment]
I'm able to see the parenthesis added opening the 02-variables.mkd in MacDown on macOS

**Comment by csev** [comment]
This is fixed.
