### ISSUE TITLE
Class and Instance Variables

### ISSUE THREAD

**Issue by cadenzasong** [csev/py4e#175]
Please correct me if I'm missing something, but I think some code examples in chapter 14 is not accurate.

e.g.
in party5.py
the "x = 0" and "name = """ is class variables (https://docs.python.org/3.7/tutorial/classes.html#class-and-instance-variables), I think it's clearer to remove them and add self.x = 0 in the constructor.﻿

**Comment by csev** [comment]
I agree - working on fixing.

**Comment by csev** [comment]
This has now been fixed i the latest version https://do1.dr-chuck.com/pythonlearn/EN_us/pythonlearn.pdf - I redid Chapter 8, all the party examples, the slides and Parts 2-4 of the lectures.  Please review.

Thanks so much. Literally without you filing this issue I would have wandered off into the sunset being wrong.  So thanks.
