### ISSUE TITLE
Ch 10: Tuple assignment. the variable m in the examples is actually a list

### ISSUE THREAD

**Issue by djmartz77** [csev/py4e#180]
In the 'Tuple Assignment' section of Chapter 10 there are 3 code examples where the example shows operations on a list rather than a tuple.
### First:
    >>> m = [ 'have', 'fun' ]
    >>> x, y = m
    >>> x
    'have'
    >>> y
    'fun'
    >>>

**should be:**
    >>> m = ( 'have', 'fun' )
    >>> x, y = m
    >>> x
    'have'
    >>> y
    'fun'
    >>>

### Second:
    >>> m = [ 'have', 'fun' ]
    >>> x = m[0]
    >>> y = m[1]
    >>> x
    ' have'
    >>> y
    'fun'
    >>>

**should be:**
    >>> m = [ 'have', 'fun' ]
    >>> x = m[0]
    >>> y = m[1]
    >>> x
    ' have'
    >>> y
    'fun'
    >>>

### Third(and last):
    >>> m = [ 'have', 'fun' ]
    >>> (x, y) = m
    >>> x
    'have'
    >>> y
    'fun'
    >>>

**should _probably_ be:**
    >>> m = [ 'have', 'fun' ]
    >>> (x, y) = m
    >>> x
    'have'
    >>> y
    'fun'
    >>>

I say _probably_ because technically this does show use of a tuple in an assignment, but I suspect the intent was to show a tuple on both sides of the assignment operator.

**Comment by mbless** [comment]
I came here to let you know that this might be an error. This chapter speaks about tuple and we have a lot of example with list. Example works fine but I believe this was not the aim of this chapter.

**Comment by csev** [comment]
I agree and have changed this.
