### ISSUE TITLE
Typo in Chapter 10 footnote

### ISSUE THREAD

**Issue by mefergus** [csev/py4e#185]
The start of Chapter 10 - Tuples has a "Fun fact" footnote:

A tuple^[Fun fact: The word "tuple" comes from the names given to sequences of numbers of varying lengths: single, double, triple, quadruple, quituple, sextuple, septuple, etc.]

Here quituple should be quintuple.

**Comment by csev** [comment]
Fixed in b82a7978e91062167d0a08dabd811da774513e0d - thanks.
