### ISSUE TITLE
Tiny spelling mistake or not?

### ISSUE THREAD

**Issue by lindangulopez** [csev/py4e#187]
Exercises
Exercise 2: Write a program that categorizes each mail message by which day of the week the **commit** was done. To do this look for lines that start with "From", then look for the third word and keep a running count of each of the days of the week. At the end of the program print out the contents of your dictionary (order does not matter).

should be  **comment**?

**Comment by srcatto** [comment]
Commit is correct, check the data,
From stephen.marquard@uct.ac.za Sat Jan  5 09:14:16 2008
It's the day it's sent / committed in other words.
