### ISSUE TITLE
Party5.py code in ch14 outputs wrong

### ISSUE THREAD

**Issue by mrbrodeur** [csev/py4e#194]
Dear Prof Sev,

The code in party5.py on the Chapter 14 page initiates 'Sally' and 'Jim' but then shows the code as printing out Sally, then Sally-Party, then Jim and Jim-party.

According to the code, Sally and Jim should initiate first, but according the the box that shows the output, Sally initiates, then parties, then Jim initiates, then Jim parties. 
<img width="570" alt="screen shot 2019-01-04 at 1 35 10 pm" src="https://user-images.githubusercontent.com/46334979/50704650-1e05a980-1026-11e9-8a07-aaa21af338fd.png">

**Comment by csev** [comment]
Note that the order for party5 and party6 is different - but the bug you found in the party5 output has been fixed in the book.
