### ISSUE TITLE
Ch15: .sqlite or .sqlite3 - file extension in twspider.py

### ISSUE THREAD

**Issue by mrbrodeur** [csev/py4e#195]
Dear Prof Sev,

The code for twspider.py shows that the database created is 'spider.sqlite'.

In the chapter text immediately below the code, the file is described as 'spider.sqlite3'.

I expect that these should both be consistent, either both one or the other?

https://www.py4e.com/html3/15-database

**Comment by csev** [comment]
As of January 2024, this code is no longer supported as Twitter has been removed form the book completely.  The Coursera course will remove all Twitter related material in the first half of 2024.
