### ISSUE TITLE
Slides Chap#4 (functions) and Chap#14 (Object Oriented) are empty when downloaded

### ISSUE THREAD

**Issue by vanessaklein** [csev/py4e#207]
When downloaded
from https://www.py4e.com/lessons/Objects
you get an empty PPT file

By the way... thanks for this wonderful material!

**Comment by ayushksingh28** [comment]
No, I am getting a fully viewable ppt file.[
[Pythonlearn-14-Objects.pptx](https://github.com/csev/py4e/files/6101186/Pythonlearn-14-Objects.pptx)
](url)

**Comment by csev** [comment]
These downloads now work.  Thanks.
