### ISSUE TITLE
book3/ch13 googlemap api key-locked

### ISSUE THREAD

**Issue by Lheeli** [csev/py4e#209]
The google map API now behind a keylock:
http://maps.googleapis.com/maps/api/geocode/json?address=Ann+Arbor%2C+MI returns:
"error_message" : "You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account"

I think this will make it impossible to successfully do all the exercises, which is sad: I've been learning a lot!

**Comment by rexmzk** [comment]
I guess it's because we need api_key to request data from the Google API, but you can skip this problem and move on, because in the following exercise, Chuck has given us an alternative way to request the data, 
if api_key is False:
    api_key = 42
    serviceurl = 'http://py4e-data.dr-chuck.net/json?'
else :
    serviceurl = 'https://maps.googleapis.com/maps/api/geocode/json?'

**Comment by sharon18BQ1A05L3** [comment]
We are getting output but it is not matching the place id in auto grader . please help me to know my mistake

**Comment by csev** [comment]
Thanks - I removed the "Hey click on this URL" from the latest version of the book (January 2024)
