### ISSUE TITLE
"async" / "await" now keywords in Python, not in Chapter 2 keyword list

### ISSUE THREAD

**Issue by sciencecompliance** [csev/py4e#212]
I learned a lot from your course, which got me started well on my adventure learning Python.  As I've progressed beyond the material in your introductory course, however, I have discovered that "async" and "await" are now keywords in Python (not just part of the asyncio library).  I'm not sure which version this was changed, but, anyway, I was going back through your online material to see if there was anything I missed or just needed to jog my memory on.  When I was skimming Chapter 2, I noticed that they were not included in you keyword list.

**Comment by csev** [comment]
Thanks - I added them
