### ISSUE TITLE
No Mention of Sets / Frozen Sets

### ISSUE THREAD

**Issue by sciencecompliance** [csev/py4e#213]
This is the second issue I've raised about your course, which is very good, by the way.  One area in which I think it could improve, however, as I've progressed and learned more about Python is the complete lack of any mention of sets or frozen sets in the literature.  Before getting into more advanced concepts like data visualization that require third-party libraries, I think it might be useful to just round the bases and mention sets/frozen sets with the other data structures, especially since the syntax is somewhat similar to that of dictionaries (with curly braces) as well as their unique capabilities for comparison.  Once one understands lists, dictionaries, and tuples, I see no reason why it wouldn't be easy to just learn sets as well.

**Comment by csev** [comment]
Thanks for the thought but this book is not intending to be a complete description of Python.  You will notice that there is no mention of things like lambdas or recursion because I feel they confuse the beginning learner.  Frozen sets - very confusing.
