### ISSUE TITLE
Ch. 3, Exercise 2 issue

### ISSUE THREAD

**Issue by douano** [csev/py4e#226]
Exercise 2: Rewrite your pay program using try and except so that your program handles non-numeric input gracefully by printing a message and exiting the program. The following shows two executions of the program:

Enter Hours: 20
Enter Rate: nine
Error, please enter numeric input

**Enter Hours: forty
Error, please enter numeric input**

I tried the attached code to trigger the except when the user inputs the hours as a string, but it didn't seem to work.  Where am I going wrong?

<img width="791" alt="Screen Shot 2019-10-04 at 9 03 04 PM" src="https://user-images.githubusercontent.com/56481791/66703503-44f1ba00-ece1-11e9-9ab9-5a9ec385f2c3.png">

**Comment by douano** [comment]
Apologies - my program attempt re-attached:
<img width="848" alt="Screen Shot 2019-10-12 at 11 12 49 AM" src="https://user-images.githubusercontent.com/56481791/66703511-694d9680-ece1-11e9-98e5-8519879d846f.png">

**Comment by haihaola** [comment]
What was your output, @douano?

**Comment by srcatto** [comment]
This is not the correct place to ask for worked example help. The code is doing exactly the code you wrote for bad hours. Please use the correct forums on Coursera, edX, other MOOC site you are using.
