### ISSUE TITLE
Chapter 12 - example looks to be missing context parameter

### ISSUE THREAD

**Issue by vorian77** [csev/py4e#229]
<img width="733" alt="Screen Shot 2019-11-23 at 10 47 53 AM" src="https://user-images.githubusercontent.com/1355098/69481403-10444880-0ddf-11ea-9ece-be40fc0710b7.png">

Under the section: Parsing HTML using regular expressions
I received the following error when I ran the example code:
**ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)**

I added the context (as specified in your following code example) and it worked fine.

P.S. Dr. Chuck, I'm a fellow Wolverine who is learning Python for a late-stage career change. I love the course. It's been tremendously helpful. Thanks for all you've done to promote Python. Phyllip

**Comment by srcatto** [comment]
The code has that change already, dated about 1.5 months ago.
https://www.py4e.com/code3/urlregex.py

**Comment by csev** [comment]
It takes a while to get the latest changes into the print book - but the online books are all updated.
