### ISSUE TITLE
Code in intro, minor improvement

### ISSUE THREAD

**Issue by wstomv** [csev/py4e#241]
In https://github.com/csev/py4e/blob/master/book3/01-intro.mkd, I would like to suggest  to improve readability by adding a space after the colon in:
``` shell
python words.py
Enter file:words.txt
to 16
```
I.e., replace it by
``` shell
python words.py
Enter file: words.txt
to 16
```

**Comment by csev** [comment]
This has been fixed in the latest version of the book (January 2024).  Thanks.
