### ISSUE TITLE
Typo in Ch. 15/twspider

### ISSUE THREAD

**Issue by zjfelling** [csev/py4e#247]
This is part of the 'Spidering Twitter using a database' section:

        "cur.execute('''INSERT INTO Twitter (name, retrieved, friends)
            VALUES ( ?, 0, 1 )''', ( friend, ) )"

"we use the SQL INSERT statement to add the friend's screen_name to the table with an indication that we have not yet retrieved the screen_name and set the friend count to **zero**."

The friend count is different than the retrieval indicator, and we set it to **one** in the code. At the very least it seems ambiguous to equate the retrieval count and friend count given there is a friends count.

**Comment by csev** [comment]
Thanks.

**Comment by csev** [comment]
It will take about an hour for the HTML and PDF copies to be updated.  I have no good way to fix the already printed copies :)  Thanks.
