### ISSUE TITLE
twspider.py Minor Correction

### ISSUE THREAD

**Issue by zjfelling** [csev/py4e#248]
There is a minor inconsistency with how the twspider.py code is presented in chapter 15.

"    url = twurl.augment(TWITTER_URL, {'screen_name': acct, 'count': '**5**'})
    print('Retrieving', url)   " is used early in the section showing the intent to retrieve a count of 5 
                                           friends.

However, later in the section, examples showing the code running have the script retrieving 20 accounts per search without any explanation for this change.

**Comment by csev** [comment]
Thanks.
