### ISSUE TITLE
New typo on Ch. 15, missing codequote

### ISSUE THREAD

**Issue by sixsixseven** [csev/py4e#252]
Possibly missing `[0]` in the following sentence (underlined):

>Since `fetchone()` returns the row as a *tuple* (even though there is only one field), we take the first value from <ins>the tuple using to get</ins> the current friend count into the variable `count`.

Should read:

>Since `fetchone()` returns the row as a *tuple* (even though there is only one field), we take the first value from the tuple using `[0]` to get the current friend count into the variable `count`.

**Comment by csev** [comment]
This whole example has been deleted as of January 24 - with the great "Twitter purge" in the book.
