### ISSUE TITLE
Ch.13  -  Video Missing

### ISSUE THREAD

**Issue by timmid1** [csev/py4e#256]
In the video tutorials for Chapter 13, one video is there twice and the video which probably should include JSON is missing.  This is a great course and I miss the video tutorials!
Thank you,
Tim-

**Comment by henry-001** [comment]
You can get the videos straight from youtube ( https://www.youtube.com/watch?v=vjQZscHOaG4&list=PLlRFEj9H3Oj7Bp8-DfGpfAfDBiblRfl5p&index=67 )

**Comment by timmid1** [comment]
Thank you Henry-001.  That youtube page provides a very full set of video tutorials.

**Comment by csev** [comment]
Hey @timmid1 I am looking at https://www.py4e.com/lessons/servces and see nothing duplicate or missing.  Here is the file that describes that module:  
https://github.com/csev/py4e/blob/master/lessons.json#L763
The next few lines are the YouTube that make up the module - I neither see a missing nor a duplicate - but would love it if you found something.
