### ISSUE TITLE
third_exam_chapter_13-Adjust_test_data_result

### ISSUE THREAD

**Issue by ClenioCampolina** [csev/py4e#258]
In the third exam of chapter 13, the **test data** result is incorrect (probably it is the value the user would get from the former Google maps API).

In the test you can see:

"Test Data / Sample Execution

You can test to see if your program is working with a location of "South Federal University" which will have a place_id of "ChIJy0Uc1Zmym4gR3fmAYmWNuac"."

If you enter "South Federal University" as your address when using 'http://py4e-data.dr-chuck.net/json?' as your API endpoint, you get "ChIJ0V94rPl_bIcRqLdrlbjFMDk" instead of "ChIJy0Uc1Zmym4gR3fmAYmWNuac".

**Comment by csev** [comment]
This has been removed from the book.
