### ISSUE TITLE
Video link isn't available anymore : youtube.com/watch?v=mf-kCFz0MEin Web Services- E- serviceOriented Approach 

### ISSUE THREAD

**Issue by NickB1520** [csev/py4e#284]
In this video on the course, Ch. 13 , the above videolink isn't available anymore. I found another video : title: " What is an API?" Very good explained for newones, like me, what exactly an API is on several examples. If this was the right intention, maybe this link in the video could be replaced ( if mule soft and py4e agrees). (Link: https://www.youtube.com/watch?v=s7wmiS2mSXY mule soft)

**Comment by csev** [comment]
Thanks. Where is this video linked from?   It is not linked from www.py4e.com directly?  Is the link inside a video?

**Comment by NickB1520** [comment]
Good morning,sorry. I forgot to mention. The video link is inside the video. 

  

    Am Samstag, 13. Februar 2021, 14:09:55 MEZ hat Charles Severance <notifications@github.com> Folgendes geschrieben:  
 
 


Thanks. Where is this video linked from? It is not linked from www.py4e.com directly? Is the link inside a video?
