### ISSUE TITLE
Ch 15 tracks.py traceback on pythonanywhere 

### ISSUE THREAD

**Issue by NickB1520** [csev/py4e#287]
Need help!  If I wanna run this code on pythonanywhere I get this Traceback but I don't understand why. I stored the files also Library.xml. I tested also to run at bash console. The same problem.
Enter file name: Library.xml
Traceback (most recent call last):
  File "/home/Nic15/tracks.py", line 48, in <module>
    stuff = ET.parse(fname)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
  File "<string>", line None
xml.etree.ElementTree.ParseError: syntax error: line 3, column 72

**Comment by csev** [comment]
It worked for me:
<pre>
19:28 ~/py4e $ curl -O https://www.py4e.com/code3/tracks/Library.xml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  637k    0  637k    0     0  3989k      0 --:--:-- --:--:-- --:--:-- 4008k
19:28 ~/py4e $ head Library.xml 
&lt;?xml version="1.0" encoding="UTF-8"?>
&lt;DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
&lt;plist version="1.0">
&lt;dict>
        &lt;key>Major Version</key><integer>1</integer>
        <&lt;key>Minor Version</key><integer>1</integer>

19:28 ~/py4e $ curl -O https://www.py4e.com/code3/tracks/tracks.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2268    0  2268    0     0  22677      0 --:--:-- --:--:-- --:--:-- 22909
19:29 ~/py4e $ python3 tracks.py 
Enter file name: Library.xml
Dict count: 404
Another One Bites The Dust Queen Greatest Hits 55 100 217103
Asche Zu Asche Rammstein Herzeleid 79 100 231810
Beauty School Dropout Various Grease 48 100 239960
Black Dog Led Zeppelin IV 109 100 296620
Bring The Boys Back Home Pink Floyd The Wall [Disc 2] 33 100 87118)
</pre>
