### ISSUE TITLE
Typo Chapter 14 Python Objects

### ISSUE THREAD

**Issue by hchjackson** [csev/py4e#290]
There is a typo in the HTML book https://www.py4e.com/html3/14-objects
It's located in the **Object lifecycle** section.

In the sentence, "It actually “thows our object away” so it can reuse the an variable to store the value 42." (This is located toward the end of the section, above the **Multiple instances** header.)

The word "thows" should be "throws".

**Comment by csev** [comment]
Thanks - I just fixed this in all the copies of the book.
