### ISSUE TITLE
French Translation Request

### ISSUE THREAD

**Issue by Bam92** [csev/py4e#296]
Hey!

I'm writing to request for french translation of the book. What do I need to do ?

**Comment by csev** [comment]
Are you saying you want to help with a translation?

**Comment by Bam92** [comment]
Yes, of course.

**Comment by csev** [comment]
Wonderful - please send email to csev at umich.edu - an issue is a pretty clunky way to chat :)  Thanks.

**Comment by Bam92** [comment]
I've already sent an email.

**Comment by ericlery** [comment]
> Wonderful - please send email to csev at umich.edu - an issue is a pretty clunky way to chat :) Thanks.

I’m in too ✋
