### ISSUE TITLE
Not able to use Twitter API

### ISSUE THREAD

**Issue by NDhingra01** [csev/py4e#341]
# Hey, Thank you for clicking please read till the end
---
### I have been facing several difficulties while dealing with Twitter API
- First of all, I don't know how to make a Twitter app with the permission of 'Read and Write'
- Secondly, Even if I generate key and secret so the permission is 'Read and Write' so it gives an authentication error
- It becomes really frustrating when you can't find a good tutorial on Youtube and you want to learn 
```
If anyone can support that would be great and extremely helpful. Thankyou 🙏
@csev Can you attach a video on how to operate dev.twitter.com nowadays because it feels a bit hard to use it. Thankyou for reading and your Time```

**Comment by csev** [comment]
We are not going to support the twitter API.   They made so difficult that there is no point.  At some point we need to find another another API to work with and the book will be revised.  I will not be describing the twitter API in a future version of the book.

**Comment by Nakul-Dhingra** [comment]
Okay Sir, thankyou for the reply and my last humble request would be to inform in the book people about that becuase many people in discussions are confused

**Comment by csev** [comment]
That is a good point.
