### ISSUE TITLE
translating

### ISSUE THREAD

**Issue by pyZac** [csev/py4e#342]
hello, my name is Saqer Terkawi, I want to translate Dr-Chuck's book (python for everybody) to Arabic, I am facing trouble knowing where to start.
I need help.

**Comment by srcatto** [comment]
A few issue requests below yours, there is a french translation request, Dr. Chuck explains how to contact him, https://github.com/csev/py4e/issues/296

Or the link on the page https://www.py4e.com/materials
If you are interested in translating the book or other online materials into another language, I have provided some instructions on how to translate this course in my GitHub repository. If you are starting a translation, please contact me so we can coordinate our activities.

Are you aware that Coursera has an Arabic version of the course, there is a link on the page https://www.py4e.com/courses

**Comment by csev** [comment]
The book is now available in Arabic.

https://www.py4e.com/translations/AR/ar/book_ar_2023_01_01.pdf
