### ISSUE TITLE
emaildb.py not working 

### ISSUE THREAD

**Issue by NDhingra01** [csev/py4e#345]
# Hey, Thank you for checking this thing out. Please read till the end
So as I was using [`emaildb.py` ](https://www.py4e.com/code3/emaildb.py?PHPSESSID=b874137b59f250e1f910e14699b7c20a) and it worked fine with the file called `mbox-short.txt` but the error is when I run It with `mbox.txt` the program stops and doesn't work anymore and I was using Idle and tried it on 2-3 code editors too

  - As you guys can see, this isn't working with the `mbox.txt` file and working it with `mbox-short.txt` and just to clear I waited for 2 minutes for the file to run and tried almost 100 times so.
  -  It's really important to solve as I need it in my assignment
  -  I hope anyone will help me and @csev please give a look
  -  Thankyou :heart:

---
![image](https://user-images.githubusercontent.com/85800910/158991214-d8b435ee-a2db-469a-b4ee-22785b269dd1.png)

---
The code
```py
import sqlite3

conn = sqlite3.connect('emaildb.sqlite')
cur = conn.cursor()

cur.execute('DROP TABLE IF EXISTS Counts')

cur.execute('''
CREATE TABLE Counts (email TEXT, count INTEGER)''')

fname = input('Enter file name: ')
if (len(fname) < 1): fname = 'mbox-short.txt'
fh = open(fname)
for line in fh:
    if not line.startswith('From: '): continue
    pieces = line.split()
    email = pieces[1]
    cur.execute('SELECT count FROM Counts WHERE email = ? ', (email,))
    row = cur.fetchone()
    if row is None:
        cur.execute('''INSERT INTO Counts (email, count)
                VALUES (?, 1)''', (email,))
    else:
        cur.execute('UPDATE Counts SET count = count + 1 WHERE email = ?',
                    (email,))
    conn.commit()

# https://www.sqlite.org/lang_select.html
sqlstr = 'SELECT email, count FROM Counts ORDER BY count DESC LIMIT 10'

for row in cur.execute(sqlstr):
    print(str(row[0]), row[1])

cur.close()
```

**Comment by csev** [comment]
Hey @NDhingra01 - you generally do not want run any of the assignments for the course from a code editor because they don't end up in a known folder to read the data files.  I recommend terminal or command line to run any code that reads or writes files.
