### ISSUE TITLE
Chapter 5 Exercise 1 - "number" is underspecified

### ISSUE THREAD

**Issue by jodischneider** [csev/py4e#352]
"Number" is underspecified in Chapter 5 Exercise 1. Should this say "integer"? (All the numeric input examples are integers)
Otherwise, if "float" is intended, the output should read:
16.0 3 5.333333333333333

**Comment by srcatto** [comment]
I think 'number' is okay. This way it's not restricting the input to int. Either int / float input can be entered in the example code without changes as fval = float() makes it all the same.
