### ISSUE TITLE
Chapter 8/exercise 4:sort and print the list of unique words in alphabetical order

### ISSUE THREAD

**Issue by Tutubaibai1** [csev/py4e#374]
I'm not 100% sure the wording in the original exercise is the best option. I think if something needs to be "in alphabetical order", (from a user's perspective, not a computer's perspective) we will not expect the difference betwee capitalized words and lowercase words. In this exercise, (in my opinion) it should be:
['already', 'and', 'arise', 'breaks', 'but', 'east', 'envious', 'fair', 'grief', 'is', 'it', 'juliet', 'kill', 'light', 'moon', 'pale', 'sick', 'soft', 'sun', 'the', 'through', 'what', 'who', 'window', 'with', 'yonder']
rather than:
['Arise', 'But', 'It', 'Juliet', 'Who', 'already',
'and', 'breaks', 'east', 'envious', 'fair', 'grief',
'is', 'kill', 'light', 'moon', 'pale', 'sick', 'soft',
'sun', 'the', 'through', 'what', 'window',
'with', 'yonder']

**Comment by csev** [comment]
Thanks - take a look at https://github.com/csev/py4e/commit/e58705b25760819b4310f25713ce1d0572498bd3 to see if you agree with my fix.

**Comment by Tutubaibai1** [comment]
Thank you for the fast and effective fix. The new wording is great!

**Comment by csev** [comment]
Thanks for a well worded suggestion that made it easy to fix :)
