### ISSUE TITLE
week 6-assignment 4.6

### ISSUE THREAD

**Issue by Dale69** [csev/py4e#403]
my code has the correct output...though the error message is always...mismatch...

i still am in the early so this first obstacle really exasperates me...my code..

def computepay(hours, rate):
    if hours <= 40:
        pay = hours * rate
    else:
        pay = 40 * rate + (hours - 40) * rate * 1.5
    return pay

hours = float(input("Enter hours: "))
rate = float(input("Enter rate per hour: "))

pay = computepay(hours, rate)

print("Pay:", pay)

...

a nudge in the right directions will help tremedously...

**Comment by pravintargaryen** [comment]
Hi Dale, 

The solution is in your code itself. Just remove the colon ":" in the last line's print command. The autograder is designed to be very specific & even a single character change will result in mismatch.

**Comment by Dale69** [comment]
many many thanks…y’all rock…!Sent from my iPhoneOn Mar 31, 2023, at 12:55 AM, pravintargaryen ***@***.***> wrote:﻿
Hi Dale,
The solution is in your code itself. Just remove the colon ":" in the last line's print command. The autograder is designed to be very specific & even a single character change will result in mismatch.
