### ISSUE TITLE
Weird note formatting talking about Python 2

### ISSUE THREAD

**Issue by uzuki7777** [csev/py4e#419]
At first I thought the asterisk meant a footnote, but then I realized I think the whole note is supposed to be in italics. Instead, the italics stop at the word "Unicode" and the rest is not in italics and it actually prints two * characters. Maybe just leave everything in italics?

Quite new to github. I hope I'm doing this right!

**Comment by csev** [comment]
Could tell be a bit more about where this happens in the book?

**Comment by uzuki7777** [comment]
Hmm let's see if I can find it again 5 months later! Section 15.5 page 193.

**Comment by csev** [comment]
Thanks - if you look at the latest version of the book on www.py4e.com - you will see that I deleted the whole paragraph.  Enough time has passed that any reference to Python 2 if pretty much out of place and irrelevant.  I think it is fine now.    Feel free to take a look at https://do1.dr-chuck.com/pythonlearn/EN_us/pythonlearn.pdf and see if you think anything else needs changing.  Thanks.
