### ISSUE TITLE
💡 idea: list funciton is not necessary  In 10.5 (page 124)

### ISSUE THREAD

**Issue by Farshidmi** [csev/py4e#429]
HI, thanks for this useful books,
As a teacher  for compatibility with the next code suggest that **list** function remove in the following code in page 124 (10.5 Multiple assignment with dictionaries):

```
for key, val in list(d.items()):
    print(val, key)
```
and change it to:
```
for key, val in d.items():
    print(val, key)
```

**Comment by csev** [comment]
I agree - fixed in January 2024 version of the book.
