### ISSUE TITLE
Summary of py4e is incorrect

### ISSUE THREAD

**Issue by GTziolas** [csev/py4e#431]
I believe that the summary part of the https://github.com/csev/py4e/blob/master/book3/14-objects.mkd file is incorrect. Either the code above it or the text below the code should be corrected

**Comment by csev** [comment]
Please give me more detail where you are seeing this.  I am currently editing this chapter - so I might have broken something.  Is this on a web page, PDF, or printed book? And what is wrong.    Thanks.

**Comment by csev** [comment]
I found it and fixed it - it was indeed a bit I was editing the past few days.   Wat a few hours and check again and let me know.

**Comment by csev** [comment]
I think the fix propagated to all the online copies of the book.  Thanks so much - I probably would have missed this without your help.
