### ISSUE TITLE
Chapter 4 - Quiz: Functions - Question 5 answers

### ISSUE THREAD

**Issue by darryl-a-peterson** [csev/py4e#438]
Issue:
Should the valid answer be "x and y"? "x" is the argument to "max" but "y" is also the argument to "print"?

Question:
In the following Python code, which of the following is an "argument" to a function?

x = 'banana'
y = max(x)
print(y)

( ) print
( ) x
( ) max
( ) 'banana'

**Comment by csev** [comment]
Which site are you seeing this error?  Coursera? py4e.com ?  The quizzes are different on the various platforms.

**Comment by darryl-a-peterson** [comment]
py4e.com

**Comment by csev** [comment]
All fixed - thanks.
