### ISSUE TITLE
PY4E Quiz: Dictionaries - Python 3.7x Updates

### ISSUE THREAD

**Issue by garrettshannon** [csev/py4e#439]
Since Python 3.7x the order of key-value pairs is the same as their input order, i.e. dictionaries are now ordered structures.

**Question 1.** How are Python dictionaries different from Python lists?

 (1)Python lists can store strings and dictionaries can only store words
 **(2)Python lists maintain order and dictionaries do not maintain order**
 (3)Python dictionaries are a collection and lists are not a collection
 (4)Python lists store multiple values and dictionaries store a single value

**Question 6.** (T/**F**) When you add items to a dictionary they remain in the order in which you added them.

**PY4E Quiz says Q1 is (2) and Q6 is (F).** 

PS I'm teaching myself python via PY4E and watching the videos on Coursera. This is an amazing resource. Thank you!

**Comment by csev** [comment]
I fixed these on www.py4e.com - but Coursera has locked changes to quizzes in their existing too so a fix will take more time.

**Comment by csev** [comment]
I fixed them on Coursera as well.  Thanks.
