### ISSUE TITLE
Three dot what? (Python versions)

### ISSUE THREAD

**Issue by eah13** [csev/py4e#90]
Some of the materials for this book reference Python 3.0.  I think there's one too many significant figures in there.  It'd be more correct to say "Python 3"; Python 3.0 has been obsolete since the release of Python 3.1 on June 27th, 2009 :)

For the official supported subversion of the language, I think it'd be best to pick a recommended subversion such as 3.4 or 3.5 and note it in the preface or introduction.  "Will work with Python 3.X or later" or etc.  We may be compatible with Python 3.0 but someone should probably[1] go through in a venv and check.  Major versions are (theoretically) backwards compatible so whatever the subversion is we should be good for all future 3.Xs.  bs4 or some other third party module is likely to be the limiting factor on this- they often like to use the latest.

[1] - "someone should probably" means "I'll do this eventually if no one else does, but I hope someone else does"

**Comment by csev** [comment]
Just do it :)

**Comment by eah13** [comment]
I thought you might say something like that :)

**Comment by csev** [comment]
I don't have the expertise to know what to say here - I am a recent member of the Python 3.0 club.

**Comment by csev** [comment]
Fixed in the January 2024 version of the book.
